# Generated by Django 3.2.5 on 2022-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('about', models.CharField(default='', max_length=5000)),
                ('heading0', models.CharField(default='', max_length=500)),
                ('cheading0', models.CharField(default='', max_length=5000)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('cheading1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=500)),
                ('cheading2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
